name: Build Windows EXE
on:
  workflow_dispatch: {}
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          architecture: 'x64'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements_txt.txt

      - name: Build EXE (onefile, no console)
        run: |
          python build_script.py --onefile --name BVBChecker --noconsole

      - name: Package installer zip
        run: |
          copy dist\BVBChecker.exe BVBChecker.exe
          if not exist install.bat ( echo install.bat fehlt & exit /b 1 )
          powershell Compress-Archive -Path BVBChecker.exe, install.bat -DestinationPath BVBChecker_Installer.zip -Force

      - name: Upload installer zip
        uses: actions/upload-artifact@v4
        with:
          name: BVBChecker-Installer
          path: BVBChecker_Installer.zip


      - name: Upload EXE artifact
        uses: actions/upload-artifact@v4
        with:
          name: BVBChecker-exe
          path: dist/BVBChecker.exe


